package employee_skills.backend.persistence.database.postgresql.table;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DbEmployeeSkillsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    long countByExample(DbEmployeeSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int deleteByExample(DbEmployeeSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("employeeNo") String employeeNo, @Param("skillId") Long skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int insert(DbEmployeeSkills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int insertSelective(DbEmployeeSkills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    List<DbEmployeeSkills> selectByExample(DbEmployeeSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    DbEmployeeSkills selectByPrimaryKey(@Param("employeeNo") String employeeNo, @Param("skillId") Long skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbEmployeeSkills record, @Param("example") DbEmployeeSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbEmployeeSkills record, @Param("example") DbEmployeeSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbEmployeeSkills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_skills
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbEmployeeSkills record);
}