package employee_skills.backend.persistence.database.postgresql.table;

import java.sql.Timestamp;

import lombok.Builder;
import lombok.Value;

@Value
@Builder
public class DbEmployeeSkills {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_skills.employee_no
     *
     * @mbg.generated
     */
    private String employeeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_skills.skill_id
     *
     * @mbg.generated
     */
    private Long skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_skills.insert_datetime
     *
     * @mbg.generated
     */
    private Timestamp insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_skills.update_datetime
     *
     * @mbg.generated
     */
    private Timestamp updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_skills.insert_user_id
     *
     * @mbg.generated
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_skills.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;
}