package employee_skills.backend.persistence.database.postgresql.table;

import java.sql.Timestamp;

import lombok.Builder;
import lombok.Value;

@Value
@Builder
public class DbGenre {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.genre_id
     *
     * @mbg.generated
     */
    private Integer genreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.genre_name
     *
     * @mbg.generated
     */
    private String genreName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.insert_datetime
     *
     * @mbg.generated
     */
    private Timestamp insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.update_datetime
     *
     * @mbg.generated
     */
    private Timestamp updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.insert_user_id
     *
     * @mbg.generated
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column genre.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;
}