package employee_skills.backend.persistence.database.postgresql.table;

import java.sql.Timestamp;

import lombok.Builder;
import lombok.Value;

@Value
@Builder
public class DbSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_id
     *
     * @mbg.generated
     */
    private Integer skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_name
     *
     * @mbg.generated
     */
    private String skillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.genre_id
     *
     * @mbg.generated
     */
    private Long genreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.insert_datetime
     *
     * @mbg.generated
     */
    private Timestamp insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.update_datetime
     *
     * @mbg.generated
     */
    private Timestamp updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.insert_user_id
     *
     * @mbg.generated
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;
}